import type { Account, Transaction, TransactionCategory } from "@/types"

export const accounts: Account[] = [
  {
    id: "1",
    name: "BCA",
    type: "bank",
    balance: 5000000,
    isSavings: true,
    color: "bg-blue-500",
  },
  {
    id: "2",
    name: "Mandiri",
    type: "bank",
    balance: 2500000,
    isSavings: false,
    color: "bg-yellow-500",
  },
  {
    id: "3",
    name: "ShopeePay",
    type: "ewallet",
    balance: 150000,
    isSavings: false,
    color: "bg-orange-500",
  },
  {
    id: "4",
    name: "GoPay",
    type: "ewallet",
    balance: 75000,
    isSavings: false,
    color: "bg-green-500",
  },
  {
    id: "5",
    name: "OVO",
    type: "ewallet",
    balance: 200000,
    isSavings: false,
    color: "bg-purple-500",
  },
  {
    id: "6",
    name: "CASH",
    type: "bank",
    balance: 500000,
    isSavings: false,
    color: "bg-gray-500",
  },
]

export const transactionCategories: TransactionCategory[] = [
  {
    id: "1",
    name: "Pengeluaran",
    type: "expense",
    subcategories: [
      "Belanja Bulanan",
      "Internet",
      "Bensin",
      "Hiburan",
      "Makan & Minum",
      "Transport",
      "Kesehatan",
      "Pendidikan",
    ],
  },
  {
    id: "2",
    name: "Pemasukan",
    type: "income",
    subcategories: ["Gaji", "Freelance", "Bonus", "Investasi", "Hadiah", "Lainnya"],
  },
  {
    id: "3",
    name: "Mutasi",
    type: "transfer",
    subcategories: ["Transfer Antar Akun", "Tarik Tunai", "Top Up", "Setor Tunai"],
  },
  {
    id: "4",
    name: "Hutang",
    type: "debt",
    subcategories: [
      "Kartu Kredit",
      "Pinjaman Bank",
      "Pinjaman Online",
      "Hutang Pribadi",
      "Cicilan Barang",
      "KTA (Kredit Tanpa Agunan)",
      "Mortgage",
      "Lainnya",
    ],
  },
]

export const transactions: Transaction[] = [
  {
    id: "1",
    date: "2024-01-15",
    description: "Gaji Bulanan",
    amount: 5000000,
    type: "income",
    category: "Pemasukan",
    subcategory: "Gaji",
    accountId: "1",
  },
  {
    id: "2",
    date: "2024-01-14",
    description: "Belanja Groceries",
    amount: -250000,
    type: "expense",
    category: "Pengeluaran",
    subcategory: "Belanja Bulanan",
    accountId: "2",
  },
  {
    id: "3",
    date: "2024-01-13",
    description: "Freelance Project",
    amount: 1500000,
    type: "income",
    category: "Pemasukan",
    subcategory: "Freelance",
    accountId: "1",
  },
  {
    id: "4",
    date: "2024-01-12",
    description: "Transfer ke ShopeePay",
    amount: -100000,
    type: "transfer",
    category: "Mutasi",
    subcategory: "Top Up",
    accountId: "2",
    toAccountId: "3",
  },
  {
    id: "5",
    date: "2024-01-11",
    description: "Makan Siang",
    amount: -35000,
    type: "expense",
    category: "Pengeluaran",
    subcategory: "Makan & Minum",
    accountId: "3",
  },
]
